# Generated by Django 3.2 on 2021-04-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
