# Generated by Django 3.2 on 2021-04-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_movieproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieproxy',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
